{
 "title": "requests",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_total_by_method_total[5m])) by (method)"
    }
   ]
  },
  {
   "title": "CPU usage [ms]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 1000",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Response status codes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(django_http_responses_total_by_status_total[5m])) by(status)"
    }
   ]
  },
  {
   "title": "Memory usage [Mb]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Latenca",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_including_middlewares_seconds_sum[5m])\r\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Garbage collection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(python_gc_collections_total[5m])) by (job)"
    }
   ]
  }
 ]
}