services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_DATABASE: user
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - .db_data:/var/lib/mysql
    ports:
      - "33066:3306"