# values.yaml

user:
  replicaCount: 3

  image:
    repository: registry.digitalocean.com/rso-vaje/service-user
    tag: "latest"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8000

  env:
    secrets:
      name: django-k8s-user-prod-env
    variables:
      - name: PORT
        value: "8000"

  probes:
    livenessProbe:
      httpGet:
        path: /api/users/health
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /api/users/health
        port: 8000
      initialDelaySeconds: 3
      periodSeconds: 5

  imagePullSecrets:
    - name: registry-rso-vaje

  autoscaling:
    enabled: false  # Set to true to enable Horizontal Pod Autoscaler (HPA)
    minReplicas: 1  # Minimum number of replicas
    maxReplicas: 5  # Maximum number of replicas
    targetCPUUtilizationPercentage: 80

prometheus:
  name: prometheus
  replicaCount: 1

  image:
    repository: prom/prometheus
    tag: v2.43.0
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 9090

  volumeMounts:
    - name: config-volume
      mountPath: /etc/prometheus

  volumes:
    - name: config-volume
      configMap:
        name: prometheus-configmap

  autoscaling:
    enabled: false  # Set to true to enable Horizontal Pod Autoscaler (HPA)
    minReplicas: 1  # Minimum number of replicas
    maxReplicas: 5  # Maximum number of replicas
    targetCPUUtilizationPercentage: 80

  scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: 'localhost:9090'

    - job_name: 'service-user'
      static_configs:
        - targets: 'user.default.svc.cluster.local:8000'

    - job_name: 'service-book'
      static_configs:
        - targets: 'book.default.svc.cluster.local:8001'

    - job_name: 'service-borrow'
      static_configs:
        - targets: 'borrow.default.svc.cluster.local:8002'

    - job_name: 'service-frontend'
      static_configs:
        - targets: 'frontend.default.svc.cluster.local:80'

grafana:
  name: grafana
  replicaCount: 1

  image:
    repository: grafana/grafana
    tag: 8.4.5
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 3000

  env:
    variables:
      - name: GF_SECURITY_ADMIN_PASSWORD
        value: "admin"

  autoscaling:
    enabled: false  # Set to true to enable Horizontal Pod Autoscaler (HPA)
    minReplicas: 1  # Minimum number of replicas
    maxReplicas: 5  # Maximum number of replicas
    targetCPUUtilizationPercentage: 80


ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host:
      paths:
        - path: /api/users
          pathType: Prefix
          service:
            port:
              number: 8000

serviceAccount:
  create: true
  name: ""