apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  prometheus.yml: |
    scrape_configs:
    {{- range .Values.prometheus.scrape_configs }}
    - job_name: '{{ .job_name }}'
      static_configs:
        - targets:
            {{- range .static_configs }}
            - '{{ .targets }}'
            {{- end }}
    {{- end }}
