apiVersion: v1
kind: Service
metadata:
  name: {{ include "user.fullname" . }}
spec:
  type: {{ .Values.user.service.type }}
  ports:
    - port: {{ .Values.user.service.port }}
      targetPort: {{ .Values.user.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "user.fullname" . }}
