apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: service-user-service
                port:
                  number: 8000
          - path: /api/borrows
            pathType: Prefix
            backend:
              service:
                name: service-borrow-service
                port:
                  number: 8002
